#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd & # Keyboard shortcuts
picom --experimental-backends & # Compositor
~/.config/polybar/launch.sh & # Status bar
xsetroot -cursor_name left_ptr & # X cursor fix
dunst & # Notifications
feh --bg-fill ~/Pictures/lov.jpg & #Set wallpaper
setxkbmap tr & # Set Keyboard layout
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 & #Set Polkit
gnome-keyring-daemon --start --components=pkcs11,secret,ssh & #Keyring
#eval $(gnome-keyring-daemon -r -d -c=ssh) &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10        
 
#BSPWM configuration
bspc config border_radius        10.5
bspc config border_width         2
bspc config window_gap           6
bspc config top_padding          30
bspc config bottom_padding       2
bspc config left_padding         2
bspc config right_padding        2
bspc config single_monocle       false
bspc config click_to_focus       true
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_by_distance    true
bspc config focus_follows_pointer true
bspc config history_aware_focus  true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config remove_disabled_monitors true
bspc config merge_overlapping_monitors true


#BSPWM coloring
bspc config normal_border_color		"#4c566a"
bspc config active_border_color		"#bf616a"
bspc config focused_border_color	"#d3869b"
bspc config presel_feedback_color	"#5e81ac"

#bspc rule -a Termite state=floating follow=on
bspc rule -a Seahorse state=floating follow=on
bspc rule -a Steam desktop='^6' follow=off
bspc rule -a Spotify desktop='^6' follow=on
bspc rule -a discord desktop='^6' follow=on
bspc rule -a mintstick state=floating follow=on
bspc rule -a cpupower-gui state=floating follow=on
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

